### ISSUE TITLE
Type Error in About section

### ISSUE THREAD

**Issue by suvam97** [hsbc/bqtools#1]
Type Error in About section

The About section of this repo has a small typo error of _teh_, which should be _the_. 

**Actual**
The code repo for bqtools-json a package for managing bigquery using json exemplar data structure and home of **teh** bqsync utility.

**Expected** 
The code repo for bqtools-json a package for managing bigquery using json exemplar data structure and home of **the** bqsync utility.

**Comment by mike-m-hsbc** [comment]
resolved
